# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5433:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./example_data.sql:/docker-entrypoint-initdb.d/example_data.sql
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
